/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* * `courier` - Courier * `express` - Express * `cargo` - Cargo
*/
export enum DeliveryClassEnum {
    Courier = 'courier',
    Express = 'express',
    Cargo = 'cargo'
}
