/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeliveryRatePoint } from '../models/DeliveryRatePoint';
import { Item } from '../models/Item';
import { HttpFile } from '../http/http';

export class DeliveryRateRequest {
    'srcPoint': DeliveryRatePoint;
    'dstPoint': DeliveryRatePoint;
    'items': Array<Item>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "srcPoint",
            "baseName": "src_point",
            "type": "DeliveryRatePoint",
            "format": ""
        },
        {
            "name": "dstPoint",
            "baseName": "dst_point",
            "type": "DeliveryRatePoint",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeliveryRateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

