/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Provider } from '../models/Provider';
import { HttpFile } from '../http/http';

export class DeliveryRate {
    'provider': Provider;
    'type': string;
    'typeDisplayName': string;
    'price': number;
    'estimatedDeliveryDate': string;
    'deliveryRangeMin': number;
    'deliveryRangeMax': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "Provider",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeDisplayName",
            "baseName": "type_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "double"
        },
        {
            "name": "estimatedDeliveryDate",
            "baseName": "estimated_delivery_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "deliveryRangeMin",
            "baseName": "delivery_range_min",
            "type": "number",
            "format": ""
        },
        {
            "name": "deliveryRangeMax",
            "baseName": "delivery_range_max",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeliveryRate.attributeTypeMap;
    }

    public constructor() {
    }
}

