/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* * `status_update` - Status Update * `price_update` - Price Update
*/
export enum EventTypeEnum {
    StatusUpdate = 'status_update',
    PriceUpdate = 'price_update'
}
