/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventTypeEnum } from '../models/EventTypeEnum';
import { HttpFile } from '../http/http';

export class OrderEvent {
    'id': number;
    'order': number;
    'eventType': EventTypeEnum;
    'eventValue': string;
    'eventValueDisplayName': string;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "EventTypeEnum",
            "format": ""
        },
        {
            "name": "eventValue",
            "baseName": "event_value",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventValueDisplayName",
            "baseName": "event_value_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return OrderEvent.attributeTypeMap;
    }

    public constructor() {
    }
}



