/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountTransaction } from '../models/AccountTransaction';
import { HttpFile } from '../http/http';

export class PaginatedAccountTransactionList {
    'count'?: number;
    'next'?: string | null;
    'previous'?: string | null;
    'results'?: Array<AccountTransaction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<AccountTransaction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaginatedAccountTransactionList.attributeTypeMap;
    }

    public constructor() {
    }
}

