/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PostPaymentApplication {
    'companyName': string;
    'companyLegalName': string;
    'bin': string;
    'address': string;
    'companySector': string;
    'phoneNumber': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "companyName",
            "baseName": "company_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyLegalName",
            "baseName": "company_legal_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "companySector",
            "baseName": "company_sector",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostPaymentApplication.attributeTypeMap;
    }

    public constructor() {
    }
}

