/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Size {
    'height': number;
    'length': number;
    'width': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": "double"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": "double"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return Size.attributeTypeMap;
    }

    public constructor() {
    }
}

