/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* * `new` - New * `courier_lookup` - Courier Lookup * `courier_found` - Courier Found * `pickup_arrived` - Pickup Arrived * `delivering` - Delivering * `delivery_arrived` - Delivery Arrived * `delivered` - Delivered * `returning` - Returning * `return_arrived` - Return Arrived * `returned` - Returned * `cancelled` - Cancelled * `cancelled_with_payment` - Cancelled With Payment * `failed` - Failed
*/
export enum StatusEnum {
    New = 'new',
    CourierLookup = 'courier_lookup',
    CourierFound = 'courier_found',
    PickupArrived = 'pickup_arrived',
    Delivering = 'delivering',
    DeliveryArrived = 'delivery_arrived',
    Delivered = 'delivered',
    Returning = 'returning',
    ReturnArrived = 'return_arrived',
    Returned = 'returned',
    Cancelled = 'cancelled',
    CancelledWithPayment = 'cancelled_with_payment',
    Failed = 'failed'
}
