/**
 * delivex API
 * Documentation of API endpoints of delivex
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class User {
    'name'?: string;
    'email': string;
    'phoneNumber': string;
    'bin'?: string;
    'address'?: string;
    'bankName'?: string;
    'bankBik'?: string;
    'bankAccountNumber'?: string;
    'postpaymentEnabled': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "bankName",
            "baseName": "bank_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "bankBik",
            "baseName": "bank_bik",
            "type": "string",
            "format": ""
        },
        {
            "name": "bankAccountNumber",
            "baseName": "bank_account_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "postpaymentEnabled",
            "baseName": "postpayment_enabled",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

